package com.snipsnap.shell

import com.snipsnap.audio.Snip
import com.snipsnap.audio.Transients

/**
 * Today's whole MORPH path, frozen: `Mutate.render`'s alignment and
 * resampling for one parent, then `morph()` with its `peak` and
 * `normalizeTo`, copied verbatim from `Mutate.kt` before BECOME touched it.
 * [BecomeTest] holds `Mutate.render` at BECOME 0 to these bytes, so "BECOME
 * 0 is today's MORPH" is a comparison with the old code, never with the new
 * code itself. Do not edit this file to follow a change in `Mutate.kt`: a
 * difference here is that change showing itself.
 */
internal object LegacyMorph {

    fun render(base: Snip, parent: Snip, amount: Float): Snip {
        val rate = base.sampleRate
        val baseAligned = alignToOnset(toStereo(base))
        val parentAligned = alignToOnset(resampled(toStereo(parent), rate))
        return morph(baseAligned, parentAligned, amount, rate)
    }

    private fun morph(base: Snip, parent: Snip, amount: Float, rate: Int): Snip {
        fun monoMags(s: Snip): Pair<List<FloatArray>, Int> {
            val mono = Snip(
                FloatArray(s.frameCount) { f -> (s.samples[f * 2] + s.samples[f * 2 + 1]) / 2f },
                1, s.sampleRate,
            )
            val mags = mutableListOf<FloatArray>()
            com.snipsnap.audio.Spectral.forEachFrame(mono) { _, _, m -> mags.add(m.copyOf()) }
            return mags to mono.frameCount
        }
        val (ma, la) = monoMags(base)
        val (mb, lb) = monoMags(parent)
        val frames = maxOf(ma.size, mb.size)
        val silence = FloatArray(com.snipsnap.audio.Spectral.BINS)
        val mixed = ArrayList<FloatArray>(frames)
        for (f in 0 until frames) {
            val a = ma.getOrElse(f) { silence }
            val b = mb.getOrElse(f) { silence }
            mixed.add(FloatArray(a.size) { i -> a[i] * (1f - amount) + b[i] * amount })
        }
        val outFrames = Math.round(la * (1f - amount) + lb * amount)
        val morphed = com.snipsnap.audio.Pghi.invert(mixed, outFrames, rate)
        val target = (peak(base.samples) * (1f - amount) + peak(parent.samples) * amount).coerceAtMost(0.99f)
        val out = FloatArray(outFrames * 2)
        for (f in 0 until outFrames) {
            out[f * 2] = morphed.samples[f]
            out[f * 2 + 1] = morphed.samples[f]
        }
        normalizeTo(out, target)
        return Snip(out, 2, rate)
    }

    private const val HOT_OPEN_RATIO = 0.1f

    private fun alignToOnset(snip: Snip): Snip {
        val onset = Transients.detect(snip).firstOrNull()?.frame ?: return snip
        if (onset <= 0) return snip
        var headPeak = 0f
        for (i in 0 until onset * 2) {
            val a = if (snip.samples[i] < 0) -snip.samples[i] else snip.samples[i]
            if (a > headPeak) headPeak = a
        }
        if (headPeak >= HOT_OPEN_RATIO * peak(snip.samples)) return snip
        return Snip(snip.samples.copyOfRange(onset * 2, snip.samples.size), 2, snip.sampleRate)
    }

    private fun toStereo(snip: Snip): Snip = when (snip.channels) {
        2 -> snip
        else -> {
            val out = FloatArray(snip.frameCount * 2)
            for (f in 0 until snip.frameCount) {
                var sum = 0f
                for (ch in 0 until snip.channels) sum += snip.samples[f * snip.channels + ch]
                val v = sum / snip.channels
                out[f * 2] = v
                out[f * 2 + 1] = v
            }
            Snip(out, 2, snip.sampleRate)
        }
    }

    private fun resampled(snip: Snip, rate: Int): Snip =
        if (snip.sampleRate == rate) snip else com.snipsnap.audio.Resampler.resample(snip, rate)

    private fun peak(samples: FloatArray): Float {
        var p = 0f
        for (v in samples) {
            val x = if (v < 0) -v else v
            if (x > p) p = x
        }
        return p
    }

    private fun normalizeTo(samples: FloatArray, target: Float) {
        val p = peak(samples)
        if (p < 1e-9f || target <= 0f) return
        val k = target / p
        for (i in samples.indices) samples[i] *= k
    }
}
